name: 'Composer install action'
description: 'Composer install with cache'

inputs:
  composer_install_options:
    required: false
    default: '--prefer-dist --no-interaction'
    description: "Options that will be added to the composer install command"

  cache_dir:
    required: true
    description: Directory that will hold the cached data.

  hash_prefix:
    required: false
    default: 1
    description: Hash prefix, useful for testing if you want to bust the cache.

runs:
  using: "composite"
  steps:
    - name: Create vendor cache folder
      shell: bash
      run: mkdir -p "${{ inputs.cache_dir }}"

    - name: Restore cache if found
      shell: bash
      run: |
        HASH="${{ inputs.hash_prefix }}_${{ hashFiles('composer.json', 'composer.lock') }}"
        COMPOSER_CACHE="${{ inputs.cache_dir }}/${HASH}.tgz"
        echo "COMPOSER_CACHE=${COMPOSER_CACHE}" >> $GITHUB_ENV        
        if [ -e "${COMPOSER_CACHE}" ]; then        
          echo "Cache HIT, restoring vendor folder from cache"
          rm -rf vendor
          touch -a "${COMPOSER_CACHE}"          
          tar -xpzf "${COMPOSER_CACHE}"
        else
          echo "Cache MISS"
        fi
        
    - name: Composer install
      shell: bash
      run: |
        composer install ${{ inputs.composer_install_options }}

    - name: Save cache
      shell: bash
      run: |
        if [ ! -f "${COMPOSER_CACHE}" ]
        then
          tar -cpzf ${COMPOSER_CACHE} vendor
        fi
        
