name: 'Composer install action'
description: 'Composer install with cache'
runs:
  using: "composite"
  steps:
    - name: Create vendor cache folder
      shell: bash
      run: |
        if [ ! -d "/home/composer-cache/vendor" ]
        then
          mkdir /home/composer-cache/vendor
        fi

    - name: Check for cache hit/miss
      shell: bash
      run: |
        hash="${{ hashFiles('composer.json', 'composer.lock') }}"
        echo "COMPOSER_HASH=$hash" >> $GITHUB_ENV
        
        if [ ! -d "/home/composer-cache/vendor/$hash" ]
        then
          echo "Cache MISS!"
          echo "COMPOSER_CACHE_MISS=true" >> $GITHUB_ENV
        else
          echo "Cache HIT!"
          echo "COMPOSER_CACHE_HIT=true" >> $GITHUB_ENV
        fi

    - name: Restore cache
      shell: bash
      if: env.COMPOSER_CACHE_HIT
      env:
        hash: ${{ env.COMPOSER_HASH }}
      run: |
        # Remove existing vendor folder if it exists
        if [ -d "/home/composer-cache/vendor/$hash/vendor" ]
        then
          echo "Found existing vendor folder, removing"
          rm -rf vendor
        fi
        
        echo "Restore vendor folder from cache"
        cp -r /home/composer-cache/vendor/$hash vendor
        
        ls vendor/

    - name: Composer install
      shell: bash
      run: |
        composer install

    - name: Save cache
      shell: bash
      if: env.COMPOSER_CACHE_MISS
      run: |
        cp -r vendor /home/composer-cache/vendor/$hash
